version: '3.8'
services:

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    environment:
      POSTGRES_USER: alex
      POSTGRES_PASSWORD: alex
      POSTGRES_DB: company
    ports:
      - "5432:5432"
    networks:
      - my-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data

  graph-ql-app:
    image: graph-ql-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/company
      SPRING_DATASOURCE_USERNAME: alex
      SPRING_DATASOURCE_PASSWORD: alex
    networks:
      - my-network
    depends_on:
      - postgres-db


networks:
  my-network:
    driver: bridge

volumes:
  db-data: